#!/usr/bin/env bash
# PoC-4 scale stack: the one entry point for docker-compose.scale.yaml (plan, section 8a).
#
#   ./scale.sh build                               # chassis, fake model server, four workloads
#   ./scale.sh up <engine> <pairs> [--events kafka|dapr]
#   ./scale.sh ps | logs [service...]
#   ./scale.sh down                                # project poc04 only, and its secrets file
#
# <engine>: echo-python, echo-pydanticai, echo-langgraph, echo-typescript, or `inprocess`
# (echo_python in the chassis process, no workload container; 1 pair only).
# <pairs>: 1, 2, or 4. Traefik answers on http://127.0.0.1:18080.
# MODEL_REPLICAS=<n> in the environment runs n fake model servers behind one name (default 1).
#
# Secrets. On the first `up`, VALKEY_PASSWORD, MINIO_ROOT_PASSWORD, the chassis's MinIO key pair,
# DAPR_API_TOKEN, and APP_API_TOKEN are generated with `openssl rand -hex 24` into .env.poc04
# next to this script (mode 600, git-ignored by `.env.*`). Compose reads it with --env-file, so
# the default `.env` (the PoC-1 LiteLLM key) is never read by this stack. Values are never
# printed. `down` deletes the file; the next `up` makes new ones.
#
# Safety. Every Compose command passes `-p poc04 -f docker-compose.scale.yaml`. Nothing here
# names a container of another project or prunes anything. Works with the bash 3.2 macOS ships.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
cd "$HERE"
SECRETS="$HERE/.env.poc04"
ENGINES="echo-python echo-pydanticai echo-langgraph echo-typescript"
TAG=poc04

usage() {
  sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 2
}

# The Compose command for this project. Extra -f and --profile arguments come after.
compose() {
  local files=(-f docker-compose.scale.yaml)
  if [[ "${EVENTS:-none}" == "dapr" ]]; then
    files+=(-f docker-compose.scale-dapr.yaml)
  fi
  local env_args=()
  [[ -f "$SECRETS" ]] && env_args=(--env-file "$SECRETS")
  docker compose -p poc04 ${env_args[@]+"${env_args[@]}"} "${files[@]}" "$@"
}

new_secret() { openssl rand -hex 24; }

ensure_secrets() {
  { set +x; } 2>/dev/null
  [[ -f "$SECRETS" ]] && return 0
  (
    umask 077
    {
      echo "# Generated by scale.sh for project poc04. Never commit; \`scale.sh down\` deletes it."
      echo "VALKEY_PASSWORD=$(new_secret)"
      echo "MINIO_ROOT_PASSWORD=$(new_secret)"
      echo "CHASSIS_S3_ACCESS_KEY=chassis-$(openssl rand -hex 8)"
      echo "CHASSIS_S3_SECRET_KEY=$(new_secret)"
      echo "DAPR_API_TOKEN=$(new_secret)"
      echo "APP_API_TOKEN=$(new_secret)"
    } >"$SECRETS"
  )
  echo "scale.sh: generated secrets in $(basename "$SECRETS") (mode 600, git-ignored)"
}

build() {
  # The images this repo builds, tagged poc04. The workloads come from their own Dockerfiles.
  docker build -q -f ../../packages/chassis/Dockerfile -t "agent-platform/chassis:$TAG" ../..
  docker build -q -f ../../packages/fake-model-server/Dockerfile \
    -t "agent-platform/fake-model-server:$TAG" ../..
  local engine
  for engine in echo-python echo-pydanticai echo-langgraph; do
    docker build -q -f "../../packages/workloads/$engine/Dockerfile" \
      -t "agent-platform/$engine:$TAG" ../..
  done
  docker build -q -t "agent-platform/echo-typescript:$TAG" ../../packages/workloads/echo-typescript
}

up() {
  local engine=${1:-} pairs=${2:-}
  shift 2 || usage
  EVENTS=none
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --events) EVENTS=${2:-}; shift 2 ;;
      *) usage ;;
    esac
  done
  case "$pairs" in 1 | 2 | 4) ;; *) echo "pairs must be 1, 2, or 4" >&2; exit 2 ;; esac
  case "$EVENTS" in none | kafka | dapr) ;; *) echo "--events: kafka or dapr" >&2; exit 2 ;; esac

  local profiles=()
  [[ "$pairs" == 2 ]] && profiles+=(--profile pairs2)
  [[ "$pairs" == 4 ]] && profiles+=(--profile pairs4)
  [[ "$EVENTS" != none ]] && profiles+=(--profile events)

  local config=scale.yaml services=()
  [[ "$EVENTS" == kafka ]] && config=scale-kafka.yaml
  [[ "$EVENTS" == dapr ]] && config=scale-dapr.yaml
  if [[ "$engine" == inprocess ]]; then
    [[ "$pairs" == 1 && "$EVENTS" == none ]] || { echo "inprocess: 1 pair, no events" >&2; exit 2; }
    config=scale-inprocess.yaml
    export WORKLOAD_IMAGE="agent-platform/echo-python:$TAG"
    services=(traefik chassis-1)
  elif [[ " $ENGINES " == *" $engine "* ]]; then
    export WORKLOAD_IMAGE="agent-platform/$engine:$TAG"
  else
    echo "engine must be one of: $ENGINES inprocess" >&2
    exit 2
  fi
  export CHASSIS_CONFIG=$config

  ensure_secrets
  # Every `up` starts from a clean project: pairs, daprd, and state of an earlier `up` (more
  # pairs, another engine) are removed first, so the count is exact and Valkey is empty.
  EVENTS=dapr compose --profile pairs4 --profile events rm -sf >/dev/null 2>&1 || true
  echo "scale.sh: $engine, $pairs pair(s), events $EVENTS, config $config"
  compose ${profiles[@]+"${profiles[@]}"} up -d --wait --no-build --remove-orphans \
    ${services[@]+"${services[@]}"}
  compose ${profiles[@]+"${profiles[@]}"} ps --format '{{.Name}}\t{{.State}}\t{{.Status}}'
}

down() {
  # Every profile, so no pair or daprd of this project is left behind. Volumes of this project
  # only (there are none today: data lives on tmpfs).
  EVENTS=dapr
  if [[ -f "$SECRETS" ]]; then
    compose --profile pairs4 --profile events down -v --remove-orphans
  else
    # The file is gone, but Compose still interpolates the required secrets: give it dummies
    # for this command only. They reach no container: `down` creates none.
    VALKEY_PASSWORD=x MINIO_ROOT_PASSWORD=x CHASSIS_S3_ACCESS_KEY=x CHASSIS_S3_SECRET_KEY=x \
      DAPR_API_TOKEN=x APP_API_TOKEN=x \
      compose --profile pairs4 --profile events down -v --remove-orphans
  fi
  rm -f "$SECRETS"
}

cmd=${1:-}
[[ -n "$cmd" ]] || usage
shift
case "$cmd" in
  build) build ;;
  up) up "$@" ;;
  down) down ;;
  ps) EVENTS=dapr; compose --profile pairs4 --profile events ps "$@" ;;
  logs) EVENTS=dapr; compose --profile pairs4 --profile events logs "$@" ;;
  *) usage ;;
esac
